project:
  type: book
  output-dir: docs

book:
  title: "Learning `data.table` Notes"
  author: "Lingyun Zhang"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - reference_semantics.qmd
    - keys_and_search.qmd
    - secondary_indices.qmd
    - examples.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



