project:
  type: book

book:
  title: "Learning `data.table` Notes"
  author: "Lingyun Zhang"
  date: today
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



